### ISSUE TITLE
How to use, not working

### ISSUE THREAD

**Issue by alemdg** [kunaldodiya/ionic-sqlite-orm#2]
Cannot find name 'QueryBuilder'.

**Comment by krunaldodiya** [comment]
let me just write full Read me, that will help :)

**Comment by alemdg** [comment]
:-) thanks

**Comment by krunaldodiya** [comment]
when done and working successfully, let me know, so I can close the issue. feel free to contribute, it would be a great help :)

**Comment by alemdg** [comment]
yes, of course.

thanks

**Comment by alemdg** [comment]
worked perfectly.

regards!

**Comment by krunaldodiya** [comment]
thanks, if you can make it work using npm install command, it would be a great help, working on other project, so don't get that much time to update :)
